apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  finalizers:
  - maistra.io/istio-operator
  name: basic
  namespace: istio-system
spec:
  runtime:
    components:
      pilot:
        deployment:
          replicas: 2
        pod:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
          - key: node-role.kubernetes.io/infra
            operator: Equal
            value: "reserved"
            effect: NoExecute
          - key: node-role.kubernetes.io/infra
            operator: Equal
            value: "reserved"
            effect: NoSchedule
  gateways:
    ingress:
      runtime:
        deployment:
          #autoScaling:
          #  enabled: true
          #  maxReplicas: 3
          #  minReplicas: 2
          autoScaling:
            enabled: false
          replicas: 3
        pod:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
          - effect: NoExecute
            key: node-role.kubernetes.io/infra
            operator: Equal
            value: reserved
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Equal
            value: reserved
    egress:
      runtime:
        pod:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
          - effect: NoExecute
            key: node-role.kubernetes.io/infra
            operator: Equal
            value: reserved
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Equal
            value: reserved
    #additionalEgress:
    #  additionalegw-egress:
    #    enabled: true
    #    namespace: bookinfo
    #    runtime:
    #      pod:
    #        nodeSelector:
    #          node-role.kubernetes.io/infra: ""
    #        tolerations:
    #        - effect: NoExecute
    #          key: node-role.kubernetes.io/infra
    #          operator: Equal
    #          value: reserved
    #        - effect: NoSchedule
    #          key: node-role.kubernetes.io/infra
    #          operator: Equal
    #          value: reserved
    #additionalIngress:
    #  additionaligw-ingress:
    #    enabled: true
    #    namespace: bookinfo
    #    runtime:
    #      pod:
    #        nodeSelector:
    #          node-role.kubernetes.io/infra: ""
    #        tolerations:
    #        - effect: NoExecute
    #          key: node-role.kubernetes.io/infra
    #          operator: Equal
    #          value: reserved
    #        - effect: NoSchedule
    #          key: node-role.kubernetes.io/infra
    #          operator: Equal
    #          value: reserved
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
      install:
        deployment:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoExecute
              key: node-role.kubernetes.io/infra
              operator: Equal
              value: reserved
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Equal
              value: reserved
    prometheus:
      enabled: true
      name: prometheus
      install:
        deployment:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoExecute
              key: node-role.kubernetes.io/infra
              operator: Equal
              value: reserved
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Equal
              value: reserved
  policy:
    type: Istiod
  profiles:
  - default
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.1
